### ISSUE TITLE
Add padding to left and right-aligned images

### ISSUE THREAD

**Issue by KillYourFM** [thundernest/thunderblog#22]
When adding images to a blog post that are left or right-aligned (with text wrap, as seen in first screenshot), the CMS' compose area shows sufficient padding between the image and text. However, the live previews and published posts display the image with no apparent padding between it and the text (second screenshot). 

We should add 5 to 10px of padding to such images to create a nicer presentation. 

<img width="944" alt="Screen Shot 2022-08-18 at 10 15 35 PM" src="https://user-images.githubusercontent.com/47599547/185486982-40b3ff82-5bef-446c-b7af-dbd8ab1dd6af.png">
<img width="903" alt="Screen Shot 2022-08-18 at 10 15 46 PM" src="https://user-images.githubusercontent.com/47599547/185487006-e9ed80c7-a661-423d-b064-ab77691b26a5.png">

**Comment by devmount** [comment]
Thank you for reporting this. Fixed in #23.
