### ISSUE TITLE
Posts navigation should be paged

### ISSUE THREAD

**Issue by Alecaddd** [thundernest/thunderblog#28]
We shouldn't use the default "old/new posts" navigation of WordPress, but enable a paged navigation.
There are a lot of very easy plugins we could use, or something like that could be coded very quickly in PHP if we don't want to rely on any external resource.
@devmount, is this something you could take care of?

**Comment by devmount** [comment]
I can do that. But I'm also packed with projects atm, so late November or start of December would be realistic for me.

**Comment by devmount** [comment]
@Alecaddd I created #33 for numbered pagination. Is this what you meant?
