### ISSUE TITLE
https://blog.thunderbird.net/favicon.ico uses invalid icon

### ISSUE THREAD

**Issue by mkmelin** [thundernest/thunderblog#43]
https://blog.thunderbird.net/favicon.ico exists but is invalid. 
It should show the Thunderbird logo, or be removed completely but it's probably better to keep it to avoid pointless 404 errors.

I'm not sure if it's referenced anywhere, but since it's a standard location software such as Thunderbird ;) may look at.

**Comment by MelissaAutumn** [comment]
I'll need to check if this is possible on a multi-site wordpress installation. The favicon linked through the meta tag works for the browser though.

**Comment by MelissaAutumn** [comment]
Talked with the folks hosting our WP install, and it's not possible to fix this issue. WP seems to intentionally host a 0-byte file to prevent browsers (and their logs) from 404'ing. 

We use a seperate favicon that's identifiable by a meta tag anyways.
