### ISSUE TITLE
Read More outside the featured post box 

### ISSUE THREAD

**Issue by ryanleesipes** [thundernest/thunderblog#7]
Take a look at the screenshot on mobile. The "Read More" button gets pushed out of the featured post box.

![Screenshot_20220204-021853.png](https://user-images.githubusercontent.com/2141621/152445681-e8199d0b-0a10-4893-9d42-35b121e9529a.png)

**Comment by devmount** [comment]
@ryanleesipes I fixed this. But you should really consider using excerpts that are not that long for posts 😅
